<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6653" started-at="2018-02-28T16:50:58Z" finished-at="2018-02-28T16:51:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6653" started-at="2018-02-28T16:50:58Z" finished-at="2018-02-28T16:51:04Z">
      <class name="com.restAPi.RestAssured.RestApiTest">
        <test-method status="PASS" signature="getTest()[pri:0, instance:com.restAPi.RestAssured.RestApiTest@1bce4f0a]" name="getTest" duration-ms="5214" started-at="2018-02-28T16:50:58Z" finished-at="2018-02-28T16:51:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTest -->
        <test-method status="FAIL" signature="postTest()[pri:0, instance:com.restAPi.RestAssured.RestApiTest@1bce4f0a]" name="postTest" duration-ms="1363" started-at="2018-02-28T16:51:03Z" finished-at="2018-02-28T16:51:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Faisal K] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Faisal K] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.restAPi.RestAssured.RestApiTest.postTest(RestApiTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postTest -->
      </class> <!-- com.restAPi.RestAssured.RestApiTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
